language: java
jdk:
  - oraclejdk8
before_script:
  - mkdir /tmp/wpilib
  - mkdir /tmp/opencv
  - wget https://github.com/wpilibsuite/allwpilib/archive/v2017.2.1.tar.gz -O /tmp/wpilib/wpilib.tar.gz
  - wget https://github.com/wpilibsuite/opencv/archive/v3.1.0-beta-3.tar.gz -O /tmp/opencv/opencv.tar.gz
  - tar -xzf /tmp/wpilib/wpilib.tar.gz
  - tar -xzf /tmp/opencv/opencv.tar.gz
  - cd tmp/wpilib
  - ./gradlew build
  - cd ../opencv
  - ./gradlew build
deploy:
  provider: releases
  api_key: "6cfb3f538a73ed7ced83a2932257109399c12aaf"
  file:
    - "$TRAVIS_BUILD_DIR/dist/RoboLib.jar"
    - "$TRAVIS_BUILD_DIR/dist/RoboLib-sources.jar"
  skip_cleanup: true
  on:
    tags: true
